name: demo

include:
  - database/compose.yml
  - app/compose.yml

services:
  dozzle:
    image: amir20/dozzle:v6.5.2
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Asia/Shanghai
    restart: always
  flower:
    image: mher/flower:2.0
    ports:
      - 5555:5555
    environment:
      - TZ=Asia/Shanghai
      - BROKER_URL=redis://:${REDIS_PASSWORD:?}@redis:6379/11
    depends_on:
      - redis
    restart: always
